### ISSUE TITLE
Change Color of DatePicker

### ISSUE THREAD

**Issue by gaetan1903** [adaptant-labs/flutter_datepicker#1]
Can you show me how to change the color of the datepicker please ?

**Comment by pmundt** [comment]
It takes the colours from `Theme.of(context)`, so if you want to change the colours beyond what's defined in your global theme, you can try wrapping the widget that calls into it with a custom [Theme()](https://api.flutter.dev/flutter/material/Theme-class.html) definition. For an example of how it's styled, refer to `example/lib/main.dart`.

**Comment by gaetan1903** [comment]
So I can't use other colors for this ???

**Comment by pmundt** [comment]
You can use any colour you like, by wrapping it in a Theme() definition, as stated above.

**Comment by gaetan1903** [comment]
Thanks !
